### ISSUE TITLE
how to activate it?

### ISSUE THREAD

**Issue by anatoli26** [Janfy/Atom-Bash-Snippets#1]
Sorry for possibly dump question, but I don't find how to activate it. When the language of the file is `shell script`, the snippets don't appear.

**Comment by Janfy** [comment]
Hi,
You nead to have the code package [Autocomplete-plus](https://atom.io/packages/autocomplete-plus) installed.

Create new file
Select Grammar **shell script**

Press **1**

=> A popup menu should be displayed

![atombash](https://cloud.githubusercontent.com/assets/717410/24655008/9167c396-193c-11e7-9fc9-3053ddd09004.gif)

**Comment by anatoli26** [comment]
@Janfy, thanks for the info! The problem was that autocomplete-plus by default had 'Minimum word length' set to 3, so the short combinations were not analyzed. Now with this setting set to '1' everything works as expected.

**Comment by Janfy** [comment]
Cool!
I don't remember i had to change this setting.
